### ISSUE TITLE
Playlist with more than 300 videos, newest ones not showing

### ISSUE THREAD

**Issue by acamposcar** [madiele/vod2pod-rss#147] opened 2024-01-30 19:31 UTC
app version: v1.1.1

- [ ] twitch api key set
- [x] youtube api key set

______
I have added a youtube playlist with more than 300 videos and the newest ones are not shown, but the oldest ones. Can you modify it to get more than 300 videos or to get the videos from the newest ones?

In case you want to try, this is the playlist I had problems with.

https://www.youtube.com/playlist?list=PL-5YtFfXdaFS5DjNzFmwwcF3ab2keYyd3

**Comment by madiele** [comment] 2024-01-30 22:32
yes, it's 300 by design, I was waiting for someone to open an issue for it it to put it as configurable, it's pretty easy to do, I will try to put something in the next release.

I'm also open to PR if anyone want's to get a shot at it before I get to it.

**Comment by madiele** [comment] 2024-02-03 09:49
@acamposcar  settings added in the beta image to test it out set `image: madiele/vod2pod-rss:beta` in the compose

to set the max results use add `- YOUTUBE_MAX_RESULTS=500` to your compose file, be mindful that a setting too high might get you rate limited by youtube, so test it out and see what works for you

I will close the issue, but feel free to reopen it if you find a bug or other issues

**Closed by madiele** 2024-02-03 09:49 UTC
Labels: good first issue

**Comment by acamposcar** [comment] 2024-02-03 10:00
Working fine! Thanks
